### ISSUE TITLE
Can't add descriptions to items with both metadata and NBT (such as the Part Builder)

### ISSUE THREAD

**Issue by aaronhowser1** [aaronhowser1/Document-Your-Mod-Mod#3]
```json
{
  "conditions": [
    {
      "type": "dym:configuration_option",
      "name": "useTinkersConstruct",
      "value": true
    }
  ],
  "for": [
    {
      "type": "dym:item_all_nbt_in_search",
      "registry_name": "tconstruct:tooltables",
      "metadata": 1
    }
  ],
  "documentation": [
    "dym.doc.tconstruct.stencil_table"
  ]
}
```

This gives `dym.doc.tconstruct.stencil_table` to all `tconstruct:tooltables` regardless of metadata

**Comment by TheSilkMiner** [comment]
This is actually working as intended, because `dym:item_all_nbt_in_search` ignores metadata and cares only about the registry name to lookup items.

I can modify this behavior and make it consider metadata, but at the moment I don't have access to my development PC.

The outline is to grab the `NonNullList` just before the return and build a new list by filtering the various ItemStacks according to metadata, returning an Immutable copy of this new list.

This could either be implented in this factory or in a new one, such as `dym:item_meta_filtered_nbt_in_search`.
